# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'analizador_lexico.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_home(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 600)
        MainWindow.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        # Crear un layout vertical para centrar la interfaz
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        
        # Agregar un espaciador para centrar el contenido
        self.verticalSpacer = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(self.verticalSpacer)

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)

        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        
        # GroupBox para el código
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        
        # Editor de código
        self.codeEditor = QtWidgets.QPlainTextEdit(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.codeEditor.setFont(font)
        self.codeEditor.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.codeEditor.setObjectName("codeEditor")
        self.verticalLayout_2.addWidget(self.codeEditor)
        
        # GroupBox para los resultados
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        
        # Visualizador de resultados
        self.resultsViewer = QtWidgets.QPlainTextEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.resultsViewer.setFont(font)
        self.resultsViewer.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.resultsViewer.setReadOnly(True)
        self.resultsViewer.setObjectName("resultsViewer")
        self.verticalLayout_3.addWidget(self.resultsViewer)
        
        # Añadir los groupboxes al layout horizontal
        self.horizontalLayout.addWidget(self.groupBox)
        self.horizontalLayout.addWidget(self.groupBox_2)
        
        self.verticalLayout.addLayout(self.horizontalLayout)

        # Espaciador para centrar el contenido hacia abajo
        self.verticalSpacer2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(self.verticalSpacer2)
        
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        
        # Botón Cargar Archivo
        self.loadButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadButton.setMinimumSize(QtCore.QSize(0, 40))
        self.loadButton.setStyleSheet("background-color: #2196F3;\n"
                                      "color: white;\n"
                                      "border: none;\n"
                                      "border-radius: 4px;")
        self.loadButton.setObjectName("loadButton")
        self.horizontalLayout_2.addWidget(self.loadButton)
        
        # Botón Analizar
        self.analyzeButton = QtWidgets.QPushButton(self.centralwidget)
        self.analyzeButton.setMinimumSize(QtCore.QSize(0, 40))
        self.analyzeButton.setStyleSheet("background-color: #4CAF50;\n"
                                         "color: white;\n"
                                         "border: none;\n"
                                         "border-radius: 4px;")
        self.analyzeButton.setObjectName("analyzeButton")
        self.horizontalLayout_2.addWidget(self.analyzeButton)
        
        # Botón Limpiar
        self.clearButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearButton.setMinimumSize(QtCore.QSize(0, 40))
        self.clearButton.setStyleSheet("background-color: #F44336;\n"
                                       "color: white;\n"
                                       "border: none;\n"
                                       "border-radius: 4px;")
        self.clearButton.setObjectName("clearButton")
        self.horizontalLayout_2.addWidget(self.clearButton)
        
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Conectamos el botón Limpiar con la función limpiar()
        self.clearButton.clicked.connect(self.limpiar)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Analizador Léxico - Primera fase - de - compilador"))
        self.label.setText(_translate("MainWindow", "Analizador Lexico, Elaborado por: Juan Ruiz, Eladio Tortolero y Yull Rodriguez"))
        self.groupBox.setTitle(_translate("MainWindow", "Código Java:"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Resultados del análisis:"))
        self.loadButton.setText(_translate("MainWindow", "Cargar Archivo"))
        self.analyzeButton.setText(_translate("MainWindow", "Analizar"))
        self.clearButton.setText(_translate("MainWindow", "Limpiar"))

    def limpiar(self):
        # Limpiar los campos de texto
        self.codeEditor.clear()
        self.resultsViewer.clear()

